const POS_LABELS: Record<string, string> = {
  'adj-f': 'prenominal adjective',
  'adj-i': 'i-adjective',
  'adj-ix': 'i-adjective (ii/yoi)',
  'adj-ku': 'ku-adjective (archaic)',
  'adj-na': 'na-adjective',
  'adj-no': 'no-adjective',
  'adj-pn': 'pre-noun adjectival',
  'adj-t': 'taru-adjective',
  adv: 'adverb',
  'adv-to': 'adverb (with to)',
  aux: 'auxiliary',
  'aux-adj': 'auxiliary adjective',
  'aux-v': 'auxiliary verb',
  conj: 'conjunction',
  cop: 'copula',
  ctr: 'counter',
  exp: 'expression',
  int: 'interjection',
  n: 'noun',
  'n-pref': 'noun prefix',
  'n-suf': 'noun suffix',
  num: 'numeric',
  pn: 'pronoun',
  pref: 'prefix',
  prt: 'particle',
  suf: 'suffix',
  unc: 'unclassified',
  v1: 'ichidan verb',
  'v1-s': 'ichidan verb (irregular)',
  'v2a-s': 'nidan verb (archaic)',
  v5aru: 'godan verb (-aru)',
  v5b: 'godan verb (-bu)',
  v5g: 'godan verb (-gu)',
  v5k: 'godan verb (-ku)',
  'v5k-s': 'godan verb (iku/yuku)',
  v5m: 'godan verb (-mu)',
  v5n: 'godan verb (-nu)',
  v5r: 'godan verb (-ru)',
  'v5r-i': 'godan verb (-ru, irregular)',
  v5s: 'godan verb (-su)',
  v5t: 'godan verb (-tsu)',
  v5u: 'godan verb (-u)',
  'v5u-s': 'godan verb (-u, irregular)',
  vi: 'intransitive verb',
  vk: 'kuru verb',
  vr: 'irregular nu verb',
  vs: 'suru verb (noun + suru)',
  'vs-c': 'su verb (classical)',
  'vs-i': 'suru verb',
  'vs-s': 'suru verb (irregular)',
  vt: 'transitive verb',
  vz: 'zuru verb',
};

export function describePos(tag: string): string {
  return POS_LABELS[tag] ?? tag;
}
