export const DAKUTEN_KEY = 'BracketLeft';
export const HANDAKUTEN_KEY = 'BracketRight';

export const KANA_KEY_MAP: Record<string, string> = {
  Digit1: 'ぬ',
  Digit2: 'ふ',
  Digit3: 'あ',
  Digit4: 'う',
  Digit5: 'え',
  Digit6: 'お',
  Digit7: 'や',
  Digit8: 'ゆ',
  Digit9: 'よ',
  Digit0: 'わ',
  Minus: 'ほ',
  Equal: 'へ',
  KeyQ: 'た',
  KeyW: 'て',
  KeyE: 'い',
  KeyR: 'す',
  KeyT: 'か',
  KeyY: 'ん',
  KeyU: 'な',
  KeyI: 'に',
  KeyO: 'ら',
  KeyP: 'せ',
  KeyA: 'ち',
  KeyS: 'と',
  KeyD: 'し',
  KeyF: 'は',
  KeyG: 'き',
  KeyH: 'く',
  KeyJ: 'ま',
  KeyK: 'の',
  KeyL: 'り',
  Semicolon: 'れ',
  Quote: 'け',
  KeyZ: 'つ',
  KeyX: 'さ',
  KeyC: 'そ',
  KeyV: 'ひ',
  KeyB: 'こ',
  KeyN: 'み',
  KeyM: 'も',
  Comma: 'ね',
  Period: 'る',
  Slash: 'め',
};

export const KANA_KEY_MAP_SHIFT: Record<string, string> = {
  Digit3: 'ぁ',
  KeyE: 'ぃ',
  Digit4: 'ぅ',
  Digit5: 'ぇ',
  Digit6: 'ぉ',
  Digit7: 'ゃ',
  Digit8: 'ゅ',
  Digit9: 'ょ',
  Digit0: 'を',
  KeyZ: 'っ',
};

export const DAKUTEN_MAP: Record<string, string> = {
  か: 'が',
  き: 'ぎ',
  く: 'ぐ',
  け: 'げ',
  こ: 'ご',
  さ: 'ざ',
  し: 'じ',
  す: 'ず',
  せ: 'ぜ',
  そ: 'ぞ',
  た: 'だ',
  ち: 'ぢ',
  つ: 'づ',
  て: 'で',
  と: 'ど',
  は: 'ば',
  ひ: 'び',
  ふ: 'ぶ',
  へ: 'べ',
  ほ: 'ぼ',
};

export const HANDAKUTEN_MAP: Record<string, string> = {
  は: 'ぱ',
  ひ: 'ぴ',
  ふ: 'ぷ',
  へ: 'ぺ',
  ほ: 'ぽ',
};
